feat:  Add NLP Engine
hpcc-systems/vcpkg pull request #26
Opened 2023-01-06 10:19 UTC by GordonSmith

Signed-off-by: Gordon Smith <GordonJSmith@gmail.com>

2023-01-09 14:25 UTC, dehilsterlexis requested changes
Just a comment on a version number. Not sure it pertains to the NLP Engine.

2023-01-09 14:25 UTC, dehilsterlexis commented on overlays/nlp-engine/vcpkg.json
> +  "version-semver": "1.21.7",
@GordonSmith is this the NLP Engine version? If so, it would need to be updated.

2023-01-09 19:38 UTC, dehilsterlexis commented on overlays/nlp-engine/vcpkg.json
> +  "version-semver": "1.21.7",
Yes.

2023-01-09 19:39 UTC, dehilsterlexis approved these changes

2023-01-10 08:14 UTC, GordonSmith commented
Fixed building on OSX

2023-01-10 08:55 UTC, merged